apiVersion: apps/v1
kind: Deployment
metadata:
  name: bqstoragereadclient-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bqstoragereadclient-1
  template:
      metadata:
        labels:
          app: bqstoragereadclient-1
      spec:
        containers:
        - name: bqstoragereadclient-1
          image: gcr.io/level-approach-382012/bq_storage_reader_client:latest